export var carTypes = [{
  cid: 0,
  class: 0,
  mode: 0,
  name: 'Aventador',
  zhName: '兰博基尼-Aventador',
  state: 'RARE',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'Aventador is one of cybercar\'s high-performance creation racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/LamborghiniGai/'
}, {
  cid: 1,
  class: 0,
  mode: 1,
  name: 'LaFerrari',
  zhName: '法拉利-LaFerrari',
  state: 'RARE',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'LaFerrari is one of cybercar\'s high-performance creation racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/Ferrair/'
}, {
  cid: 2,
  class: 0,
  mode: 2,
  name: 'Veryon',
  zhName: '布加迪-威航',
  state: 'RARE',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'Veryon is one of cybercar\'s high-performance creation racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/Bugatti/'
}, {
  cid: 3,
  class: 0,
  mode: 3,
  name: 'Agera',
  zhName: '科尼赛克-Agera',
  state: 'RARE',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'Agera is one of cybercar\'s high-performance creation racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/AGERA/'
}, {
  cid: 4,
  class: 1,
  mode: 0,
  name: 'AMG-GT',
  zhName: '奔驰AMG-GT',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'AMG-GT is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/GT50/'
}, {
  cid: 5,
  class: 1,
  mode: 1,
  name: '911',
  zhName: '保时捷-911',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: '911 is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/Porsche/'
}, {
  cid: 6,
  class: 1,
  mode: 2,
  name: 'R8',
  zhName: '奥迪R8',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'R8 is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/AudiR8/'
}, {
  cid: 7,
  class: 1,
  mode: 3,
  name: 'I8',
  zhName: '宝马i8',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'I8 is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/BMWi8/'
}, {
  cid: 8,
  class: 1,
  mode: 4,
  name: 'DB11',
  zhName: '阿斯顿马丁',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'DB11 is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/AstonMartin/'
}, {
  cid: 9,
  class: 1,
  mode: 5,
  name: 'GTR',
  zhName: '日产GTR',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'GTR is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/MaseratieGranCabrio/'
}, {
  cid: 10,
  class: 1,
  mode: 6,
  name: 'GTC',
  zhName: '玛莎拉蒂',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: 'GTC is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/MaseratieGranCabrio/'
}, {
  cid: 11,
  class: 1,
  mode: 7,
  name: '720S',
  zhName: '迈凯伦720S',
  state: 'NORMAL',
  fee: 'N ETH',
  rest: 'N',
  total: 'N',
  description: '720S is one of cybercar\'s founding racing cars and a status symbol of cybercar meta-universe.',
  modelUrl: '/cars/Mclance/'
}]

export var colors = ['black', 'white', 'red', 'blue', 'green', 'purple', 'orange', 'rainbow']
